In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

### Read the set of labels into a dataframe:

In [2]:
labels = pd.read_csv('labels.csv')

In [12]:
labels

perfect_labeler radiologist  algorithm
0            cancer      cancer       0.99
1            cancer      cancer       0.94
2            cancer      cancer       0.73
3            cancer      cancer       0.82
4            cancer      cancer       0.98
..              ...         ...        ...
144          benign      cancer       0.06
145          benign      cancer       0.98
146          benign      cancer       0.77
147          benign      cancer       0.03
148          benign      cancer       0.02

[149 rows x 3 columns]

### Start with assessing the radiologist's performance:
* Assess the _accuracy_ of the radiologist by just looking at the percent of cases that they correctly labeled
* Next, look at the true positive and true negative rates of the radiologist by generating a _confusion matrix_ 

In [5]:
radiologist_accuracy = sum(labels.perfect_labeler == labels.radiologist)/len(labels)

In [6]:
radiologist_accuracy

0.8993288590604027

In [7]:
confusion_matrix(labels.perfect_labeler.values,labels.radiologist.values,labels=["cancer","benign"])

array([[ 25,   4],
       [ 11, 109]])

### Now look at the algorithm's performance compared to the perfect labeler:
* Since the algorithm doesn't create a binary label, it instead returns a _probability_ of cancer, choose a probability cut-off to use for the algorithm's labeling of cancer vs. bening. _(Hint: 0.5 is a reasonable starting place)_
* Start with assessing _accuracy_ again here
* Generate a confusion matrix

In [16]:
def algorithm_label(row, th=0.5):
    if row['algorithm'] > th:
        return 'cancer'
    else:
        return 'benign'
    
labels['algorithm_label'] = labels.apply(lambda row: algorithm_label(row), axis=1)

In [17]:
algorithm_accuracy = sum(labels.perfect_labeler == labels.algorithm_label)/len(labels)
algorithm_accuracy

0.8926174496644296

In [18]:
confusion_matrix(labels.perfect_labeler.values,labels.algorithm_label.values,labels=["cancer","benign"])

array([[ 21,   8],
       [  8, 112]])

What happens now if you change the threshold cut-off for your algorithm's classification to 0.4? What if you raise it to 0.6? How do accuracy, fp, fn, tp, and tn change?

In [19]:
labels['algorithm_label04'] = labels.apply(lambda row: algorithm_label(row, 0.4), axis=1)

In [20]:
sum(labels.perfect_labeler == labels.algorithm_label04)/len(labels)

0.8657718120805369

In [21]:
confusion_matrix(labels.perfect_labeler.values,labels.algorithm_label04.values,labels=["cancer","benign"])

array([[ 25,   4],
       [ 16, 104]])

### Finally, let's compare our algorithm to the radiologist
* A "perfect labeler" might not exist in the real world, and in fact, if often does not
* In AI for medical imaging, using a radiologist's labels as our "true" label is often the standard of practice, and algorithm performance is judged in both an academic setting as well as in the regulated industry landscape based on performance against an expert human

* Repeat the steps above using a set threshold for your algorithm (again, 0.5 is perfectly reasonable) but now computing accuracy, tp, tn, fp, fn against the radiologist. 

In [22]:
confusion_matrix(labels.radiologist.values,labels.algorithm_label.values,labels=["cancer","benign"])

array([[ 23,  13],
       [  6, 107]])

In [23]:
sum(labels.radiologist == labels.algorithm_label)/len(labels)

0.87248322147651

## Reflection: 
* In the above exercise you assess performances of a human as well as of an algorithm against a 'perfect labeler' and also against each other. 
* Does accuracy seem like the appropriate statistic to use when evaluating these labels? Why or why not? 
* In what clinical settings does it seem more or less acceptable to have a high level of FNs? FPs? 
* How did changing the threshold on the algorithm performance change the different performance statistics? 
* How did your opinion of the algorithm's performance change when you started comparing it to a radiologist instead of the perfect labeler? What does this mean for a real-world scenario when a perfect labeler doesn't exist, and we only have a radiologist's read to base our performance on? 